typescript-kr/typescript-kr.github.io

pages/Advanced Types.md

- [typescript-kr : advanced-types](https://typescript-kr.github.io/pages/Advanced%20Types.htmll) 의 교차 타입 anchor 가 동작하지 않습니다.
- 깃북: 소문자만 동작 / 깃헙: 대, 소문자 모두 동작  하기 때문에 소문자로 수정합니다.

동작하지 않는 anchor 수정

---

pages/tutorials/TypeScript in 5 minutes.md

- [tutorials/TypeScript in 5 minutes](https://typescript-kr.github.io/pages/tutorials/TypeScript%20in%205%20minutes.html) 의 typescript 설치 안내 링크가 제대로 동작하지 않습니다.
- 다운로드 안내 링크 경로가 현재 레포에는 존재하지 않아서 [원문 링크](https://www.typescriptlang.org/download)로 수정해보았습니다.
리뷰 부탁드립니다!!

typescript-in-5-minutes 다운로드 안내 링크 수정

---

pages/Integrating with Build Tools.md

Intergrating with Build Tools 전체 검토 및 번역 (ref #54)

---

SUMMARY.md
pages/release notes/TypeScript 3.9.md

1. facebook 코멘트에 달린 릴리즈 노트 피드백 반영
> 'Unfortunately'는 '운이 안 좋게도'보다는 '안타깝게도' 정도가 더 적당한 번역 아닐까요?
2. SUMMARY.md에 TypeScript 3.9.md 추가
리뷰 부탁드립니다!!

릴리즈 노트 피드백 반영, SUMMARY.md 수정

---

pages/release notes/TypeScript 3.9.md

1. #82 릴리즈 노트 3.9 문서 업데이트
2. #80 pr 코멘트 반영 (34 라인 번역 수정)
리뷰 부탁드립니다 :)

릴리즈 노트 3.9 문서 업데이트 (resolve #82)

---

pages/compiler-options-in-msbuild.md

현재 번역 규칙에 맞춰 수정했습니다
걸프, 그런트는 원어로 바꿨는데 혹시 의견있으시면 말씀부탁드려요
resolve #53

compiler options in MSBuild 수정 (fix #53)

---

pages/tutorials/react-&-webpack.md

Update react-&-webpack.md 오타 수정입니다.

---

CONTRIBUTING.md

사소하지만 `이슈-번역 필요` url이 잘못되어 요청 드립니다.

이슈-번역 필요 url 수정

---

package.json

현재 `package.json`에 존재하는 `script` 부분 중, `test`부분이 다음과 같은 스크립트를 실행시킵니다.
`"test": "npx markdownlint . && node ./bin/lint '**/*.md'"`
`test` 스크립트는 현재 `npm run build`와 같은 스크립트를 커버하지 못하고 있어서 문제가 되고 있으며 이를 해결하기 위해 `pretest` 스크립트를 추가하고 해당 내용에 `build`와 관련된 내용을 추가했습니다.

package.json의 script에 pretest부분을 추가함

---

pages/tutorials/babel-with-typescript.md

ref #118 
내용이 많지 않아 한 번에 번역해보았습니다. 
리뷰 부탁드립니다 (_ _)

Babel with typescript issue118

---

.all-contributorsrc
README.md
pages/literal-types.md
pages/tutorials/babel-with-typescript.md

ref #115 
내용이 많지않아 한 번에 번역 진행했습니다 😄 
몇 가지 질문이 있습니다.
1. 8번째 줄, `collective type`은 어떻게 번역해야할까요?
2. 13번째 줄, `LIiteral Narrowing`을 `리터럴 축소`로 번역했는데 매끄럽지 않은 것 같아요.
3. 33번째 줄, `union type`, `type guards`, `type aliases`들은 어떻게 번역해야할까요?
리뷰 부탁드립니다. 🙇‍♀️

Literal types issue115

---

pages/tutorials/ts-for-oopers.md

깃허브 환경이 익숙하지 않아 실수가 있을 수도 있습니다 ㅠㅠ 문제 발견하시면 얼른 수정하도록 노력하겠습니다.

ts for oopers Co-learning JS까지 번역 issue#113

---

.all-contributorsrc
.github/workflows/main.yml
README.md
package-lock.json
pages/literal-types.md
pages/tutorials/ts-for-js-programmers.md

issue #112 
---
TS for JS Programmers 의 Defining Types 부분까지 번역하였습니다.
문서를 단순히 읽을 때와 이를 실제로 번역해 문서화하는 것이 느낌이 많이 다르네요..! 
번역 과정에서 의역 혹은 오역이 있는지 확인해주시면 감사하겠습니다 :)

translate TS for JS Programmers(Defining Types)

---

pages/tutorials/dom-manipulation.md

reference: #117 
처음 ~ The Document Interface 부분까지 번역 완료했습니다.
일단, 한글로 번역하기 애매한 용어 부분은 대체로 원어 그대로 사용하였습니다.
번역하다가 가장 애매했던 부분은 다음과 같습니다.
1. `line74`의 `_deprecated_` 를 번역하기 애매해서 deprecated 표기라고 번역했는데, 더 좋은 표현이 있으면 제안 부탁드립니다.
2. `line102`에서 `Which is exactly what happens;` 부분이 무슨 말인지 모르겠어서 일단, 문맥상 제가 생각하기에 어울리는 말로 번역했습니다.
3. `HTMLElement` type 표현이 많이 나오는데, TypeScript에 정의된 Interface 부분이라 생각해서 번역 용어에 따라 타입이 아닌 유형으로 번역했는데 이 부분이 적절한지 잘 모르겠습니다. 
검토해주시고 의역과 오역, 또는 제안 사항 부탁드립니다! 🙇🏻‍♀️

Translate: Dom Manipulation(~ Document Interface)

---

pages/intro-to-js-with-ts.md

Issue #110(Intro to JS with TS) 번역했습니다!
번역하면서 몇 가지 애매했던 부분들 질문 및 메모 남깁니다.
1) line10에 'A type-system based only on inference with JavaScript code.'의 inference를 '추론'이라고 번역하는 게 어색하다고 느껴집니다. 그런데 자연스러운 번역이 떠오르지 않아 직독직해를 하였는데, 더 좋은 해석이 있다면 조언 부탁드립니다 :) '타입시스템은 오직 JavaScript 코드만을 참조한다.'라는 번역도 생각해보았는데 어떻게 생각하시나요?
2) line11에 'Incremental typing'을 어떻게 해석해야할지 몰라 원문 그대로 남겼습니다. 좋은 번역, 또는 해당 문구와 관련하여 실무에서 많이 쓰는 용어가 있을까요?
3) line26에서 declaration를 '선언'이라고 번역하였는데 괜찮을까요?
4) ok를 성공, error를 오류로 번역하라고 하셨는데, 'not ok'라고 쓰여 있어 오류가 아닌 '성공 아님'으로만 일단 번역하였습니다.
마지막으로 수정/보완했으면 하는 부분 메모 남겨주시면 참고하여 수정본 올리도록 하겠습니다. 감사합니다!! :-)

1st commit: Issue #110(Intro to JS with TS) 번역

---

pages/release-notes/typescript-4.0.md

PR전에 아래의 사항들을 확인하셨나요? 확인하셨다면, 체크해주세요!
<div align=center>👆 꼭 확인해주시길 바랍니다! 👆</div>
- PR의 종류가 무엇인지 체크해주세요!
-  - [ ] Bug
-  - [x] Docs
-  - [ ] Typo
-  - [ ] etc.
PR에 대한 간단한 내용 설명을 부탁드립니다!
* Class Property Inference from Constructors 부분 번역했습니다. 
일부 용어는 https://meetup.toast.com/posts/247 이곳에서 가져다 사용했고,
아직도 이해가 잘 안 되는 부분이 있어서 코멘트 남깁니다!

class property type: first commit

---

pages/configuring-watch.md

수정요청 온것 수정하였으며, 나머지 번역 지금 작업중입니다. :)

translate configuring-watch page #96

---

pages/tutorials/dom-manipulation.md

PR전에 아래의 사항들을 확인하셨나요? 확인하셨다면, 체크해주세요!
<div align=center>👆 꼭 확인해주시길 바랍니다! 👆</div>
- PR의 종류가 무엇인지 체크해주세요!
-  - [ ] Bug
-  - [x] Docs
-  - [ ] Typo
-  - [ ] etc.
PR에 대한 간단한 내용 설명을 부탁드립니다!
*  (ref: #117) Dom Manipulation @sooyun429 님이 맡으신 부분 이후부터 끝까지 번역 진행하였습니다.
* 번역 리뷰시 중점적으로 봐주셨으면 하는 부분 함께 첨부하겠습니다.
1. `Node`, `Element` 인터페이스에 대한 이야기가 중점적으로 많이 등장하는데, 이 부분은 인터페이스명 그대로 표기하였습니다. 중간중간에 인터페이스를 지칭하는 것이 아닌 것 같은 부분은 노드, 요소로 번역했으니 이 부분에 대해 적절치 못한 부분이 있으면 의견 부탁드립니다!
2. 그 밖에, `line137`의 After capturing the `div` element 부분과 `line178`에 의역한 부분이 조금 있어서 중점적으로 봐주시면 좋을 것 같습니다! 
3. 기타 제안이나 오타 등도 잘 부탁드리겠습니다. 🙇🏻‍♀️

translate: Dom Manipulation(~ end)

---

SUMMARY.md
pages/tutorials/ts-for-js-programmers.md
pages/unions-and-intersections.md

PR전에 아래의 사항들을 확인하셨나요? 확인하셨다면, 체크해주세요!
<div align=center>👆 꼭 확인해주시길 바랍니다! 👆</div>
- PR의 종류가 무엇인지 체크해주세요!
-  - [x] Bug
-  - [x] Docs
-  - [ ] Typo
-  - [ ] etc.
PR에 대한 간단한 내용 설명을 부탁드립니다!
* 번역 완료된 문서 Summary 수정 및 오타 수정했습니다 :)

번역 완료된 문서 Summary 수정 및 오타 수정

---

pages/module-resolution.md

PR전에 아래의 사항들을 확인하셨나요? 확인하셨다면, 체크해주세요!
<div align=center>👆 꼭 확인해주시길 바랍니다! 👆</div>
- PR의 종류가 무엇인지 체크해주세요!
-  - [ ] Bug
-  - [ ] Docs
-  - [ ] Typo
-  - [x] etc.
PR에 대한 간단한 내용 설명을 부탁드립니다!
* 원문을 참고해 의미가 좀 더 명확하게 문장을 수정했습니다. :D

Path mapping 파트 번역 수정
